# -*- coding: utf-8 -*-
"""복습노트_249721_일자.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1stX9xHB0JPf9Bc3kDDJhNZDh37bZX-UZ
"""

import pandas as pd

# 샘플 데이터프레임 생성
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'email': ['alice@example.com', 'bob@example.com', 'charlie@sample.net', 'david@website.org', 'eve@domain.com'],
    'description': ['Alice is a Data Scientist.', 'Bob is an Engineer.', 'Charlie is a Doctor.', 'David is a Lawyer.', 'Eve is an Artist.']
}
df = pd.DataFrame(data)
print(df)

